openapi: 3.0.0
info:
  title: Parking App
  description: API
  version: 0.1.9

servers:
  - url: https://parking-app-api-production.up.railway.app/api
    description: production server
  - url: http://localhost:3000/api
    description: local server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  # Auth Routes
  /register:
    post:
      tags:
        - Auth
      requestBody:
        description: user registration request
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                name:
                  type: string
                password:
                  type: string
                email:
                  type: string
      responses:
        "201":
          description: user register successfully
  /login:
    post:
      tags:
        - Auth
      requestBody:
        description: user login request
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "201":
          description: user login successfully

  # Vehicle Management Routes
  /vehicle:
    post:
      tags:
        - Vehicle Management
      security:
        - bearerAuth: []
      requestBody:
        description: adding vehicle request
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                name:
                  type: string
                plateNumber:
                  type: string
                carType:
                  type: string
                userId:
                  type: string
      responses:
        "201":
          description: Vehicle added successfully!
  /vehicle/edit:
    post:
      tags:
        - Vehicle Management
      security:
        - bearerAuth: []
      requestBody:
        description: adding vehicle request
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                name:
                  type: string
                plateNumber:
                  type: string
                carType:
                  type: string
      responses:
        "201":
          description: Vehicle added successfully!
  /vehicle/delete:
    delete:
      tags:
        - Vehicle Management
      security:
        - bearerAuth: []
      requestBody:
        description: delete vehicle request
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                id:
                  type: string
      responses:
        "201":
          description: Vehicle deleted successfully!

  # Parking Zone Management Routes
  /zone:
    post:
      tags:
        - Parking Zone Management
      security:
        - bearerAuth: []
      requestBody:
        description: create parking zone request
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                name:
                  type: string
                address:
                  type: string
                costPerHour:
                  type: number
      responses:
        "201":
          description: Parking zone added successfully!
  /zone/edit:
    post:
      tags:
        - Parking Zone Management
      security:
        - bearerAuth: []
      requestBody:
        description: create parking zone request
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                name:
                  type: string
                address:
                  type: string
                costPerHour:
                  type: number
      responses:
        "201":
          description: Parking zone added successfully!
  /zone/delete:
    delete:
      tags:
        - Parking Zone Management
      security:
        - bearerAuth: []
      requestBody:
        description: delete parking zone request
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                name:
                  type: string
      responses:
        "201":
          description: Parking zone deleted successfully!

  # Reservation Management Routes
  /reservation:
    post:
      tags:
        - Reservation Management
      security:
        - bearerAuth: []
      requestBody:
        description: make reservation for the parking zone request
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                userId:
                  type: string
                vehiclePlateNumber:
                  type: string
                parkingZone:
                  type: string
                startTime:
                  type: string
      responses:
        "201":
          description: Reservation made successfully!
  /reservation/finish:
    post:
      tags:
        - Reservation Management
      security:
        - bearerAuth: []
      requestBody:
        description: finish reservation for the parking zone request
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                reservationId:
                  type: string
      responses:
        "201":
          description: Reservation finished successfully!